# Tested on iPhone 5s (10.3.3) with TotallyNotSpyware jailbreak and Meridian option, run this script on normal mode
# Also works on LukeZGD's TNS Sockport
# Might work on 10.0-10.2.1, untested

cd / && rm -rf boot lib meridian mnt User .DS_Store ._.DS_Store .cydia_no_stash .fseventsd .installed_yaluX .meridian_installed
cd /Applications && rm -rf Cydia.app Filza.app MTerminal.app Zebra.app cydown.app
cd /Library && rm -rf Frameworks LaunchDaemons MobileSubstrate PreferenceBundles PreferenceLoader Switches dpkg
cd /System/Library && rm -rf "Internet Plug-Ins" KeyboardDictionaries PreferenceBundles/AppList.bundle
cd /private/etc && rm -rf alternatives apt default dpkg dropbear pam.d profile profile.d rc.d ssh ssl sudoers symlibs.dylib
cd /sbin && rm -rf clri dmesg dump dumpfs dynamic_pager fstyp_msdos fstyp_ntfs fstyp_udf fstyp_ufs halt mount_cd9660 mount_devfs mount_fdesc mount_kernfs mount_null mount_procfs mount_synthfs mount_union newfs nologin quotacheck reboot restore tunefs umount
cd /usr && rm -rf games include local/bin local/lib
cd /usr/bin && rm -rf 7z 7za Filza [ apt-cache apt-cdrom apt-config apt-extracttemplates apt-ftparchive apt-get apt-key apt-mark apt-sortpkgs arch asu_inject awk base64 basename bashbug c_rehash captoinfo cfversion chcon chfn chown chsh cksum clear clutch cmp comm csplit curl curl-config cut cycc cydown cynject db_archive db_checkpoint db_codegen db_deadlock db_dump db_hotbackup db_load db_printlog db_recover db_stat db_upgrade db_verify df diff diff3 dircolors dirname dpkg dpkg-deb dpkg-divert dpkg-maintscript-helper dpkg-query dpkg-split dpkg-statoverride dpkg-trigger dselect du env expand expr factor find fmt fold funzip gawk getconf getty gpg gpg-zip gpgsplit gpgv groups gssc head hostid hostinfo id igawk infocmp infotocap install iofbres iomfsetgamma join jtool killall ldid ldrestart link locate login logname lzcat lzcmp lzdiff lzegrep lzfgrep lzgrep lzless lzma lzmadec lzmainfo lzmore md5sum mkfifo mktemp ncurses5-config ncursesw5-config nice nl nohup nproc nvnonce od openssl pagesize passwd paste pathchk pinky pr prepbin printenv printf ptx quota redeb renice reset respring rsync runcon sbdidlaunch sbreload scp script sdiff seq sftp sha1sum sha224sum sha256sum sha384sum sha512sum shred shuf slogin sort split ssh ssh-add ssh-agent ssh-keygen ssh-keyscan sshpass stat sudo sudoedit sum sw_vers tac tail tar tee test tic time timeout toe tput tr truncate tset tsort tty uicache uiduid uiopen unexpand uniq unlink unlzma unrar unxz unzip unzipsfx update-alternatives updatedb uptime users wc wget which who whoami xargs xz xzcat xzcmp xzdec xzdiff xzegrep xzfgrep xzgrep xzless xzmore yes zip zipcloak zipnote zipsplit
cd /usr/lib && rm -rf FilzaPass.dylib MeridianSafeMode.dylib SmartTapPs.dylib TweakLoader.dylib _ncurses apt coreutils cycript0.9 dpkg engines libST.dylib libapplist.dylib libapt-inst.dylib libapt-inst.dylib.1.1 libapt-inst.dylib.1.1.0 libapt-pkg.dylib libapt-pkg.dylib.4.6 libapt-pkg.dylib.4.6.0 libcrypto.0.9.8.dylib libcrypto.dylib libcurl.4.dylib libcurl.dylib libcurl.la libdb-4.6.dylib libdb-4.6.la libdb-4.dylib libdb.dylib libdpkg.a libdpkg.la libform.5.dylib libformw.5.dylib libformw.dylib libhistory.5.2.dylib libhistory.5.dylib libhistory.6.0.dylib libhistory.6.dylib libhistory.dylib libjailbreak.dylib liblzmadec.0.0.0.dylib liblzmadec.0.dylib liblzmadec.dylib liblzmadec.la libmenu.5.dylib libmenu.dylib libmenuw.5.dylib libmenuw.dylib libncursesw.5.dylib libncursesw.dylib libpam.1.0.dylib libpam.1.dylib libpam.dylib libpam_misc.1.dylib libpam_misc.dylib libpamc.1.dylib libpamc.dylib libpanel.5.dylib libpanel.dylib libpanelw.5.dylib libpanelw.dylib libpatcyh.dylib libprefs.dylib libreadline.5.2.dylib libreadline.5.dylib libreadline.6.0.dylib libreadline.6.dylib libreadline.dylib librocketbootstrap.dylib libssl.0.9.8.dylib libssl.dylib libsubstitute.0.dylib libsubstitute.dylib libsubstrate.0.dylib libsubstrate.dylib p7zip pam pkgconfig pspawn_hook.dylib ssl substrate terminfo tweaks xxxMobileGestalt.dylib xxxSystem.dylib
cd /usr/libexec && rm -rf _rocketd_reenable afc2d awk bigram code cydia filza frcode gnupg rmt rocketd sftp-server ssh-keysign ssh-pkcs11-helper sshd-keygen-wrapper substrate substrated sudo_noexec.dylib sudo_noexec.la vndevice
cd /usr/sbin && rm -rf ac accton chown chroot dev_mkdb edquota fdisk ioalloccount ioclasscount ioreg iostat mkfile pwd_mkdb quot quotaon repquota sshd startupfiletool sysctl update vifs vipw visudo vsdbutil zdump zic
cd /usr/share && rm -rf awk bigboss dict dpkg gnupg tabset terminfo
cd /bin && rm -rf bash bunzip2 bzcat bzip2 bzip2recover cat chgrp chmod chown cp date dd dir echo egrep false fgrep grep gunzip gzexe gzip kill launchctl ln ls mkdir mknod mktemp mv pwd readlink rm rmdir run-parts sed sh sleep stty su sync tar touch true uicache uname uncompress vdir zcat zcmp zdiff zegrep zfgrep zforce zgrep zless zmore znew