# Tested on iPhone 6 Plus (8.0), iPod Touch 6 (8.4) with wtfis jailbreak, run this script on SSH ramdisk mode
# Require manual replacement: /mnt1/usr/libexec/installd /mnt1/usr/libexec/lsd
# Possibly requires manual replacement: /mnt1/System/Library/Caches/com.apple.dyld/dyld_shared_cache_arm64

cd /mnt1 && rm -rf .cydia_no_stash .fseventsd .installed_wtfis User boot lib mnt wtfis
cd /mnt1/Applications && rm -rf Cydia.app Filza.app MTerminal.app SpringtomizeApp.app cydown.app
cd /mnt1/Library && mv LaunchDaemons/* /mnt1/System/Library/LaunchDaemons && mv NanoLaunchDaemons/* /mnt1/System/Library/NanoLaunchDaemons && rm -rf Frameworks/CydiaSubstrate.framework LaunchDaemons MobileSubstrate NanoLaunchDaemons PreferenceBundles PreferenceLoader Switches
cd /mnt1/System/Library && rm -rf KeyboardDictionaries LaunchDaemons/com.openssh.sshd.plist LaunchDaemons/com.rpetrich.rocketbootstrapd.plist LaunchDaemons/com.saurik.Cydia.Startup.plist LaunchDaemons/com.tigisoftware.filza.helper.plist PreferenceBundles/AppList.bundle && mv LaunchDaemons/com.apple.mDNSResponder.plist_ LaunchDaemons/com.apple.mDNSResponder.plist && mv LaunchDaemons/com.apple.mobile.softwareupdated.plist_ LaunchDaemons/com.apple.mobile.softwareupdated.plist && mv LaunchDaemons/com.apple.softwareupdateservicesd.plist_ LaunchDaemons/com.apple.softwareupdateservicesd.plist
cd /mnt1/private/etc && rm -rf alternatives apt default dpkg pam.d profile profile.d rc.d ssh ssl sudoers symlibs.dylib
cd /mnt1/sbin && rm -rf clri dmesg dump dumpfs dynamic_pager fstyp_msdos fstyp_ntfs fstyp_udf fstyp_ufs halt mount_cd9660 mount_devfs mount_fdesc mount_kernfs mount_null mount_procfs mount_synthfs mount_union newfs nologin quotacheck reboot restore tunefs umount
cd /mnt1/usr && rm -rf games include local/bin local/lib
cd /mnt1/usr/bin && rm -rf 7z 7za Filza [ apt-cache apt-cdrom apt-config apt-extracttemplates apt-ftparchive apt-get apt-key apt-mark apt-sortpkgs arch asu_inject awk base64 basename bashbug c_rehash captoinfo cfversion chcon chfn chown chsh cksum clear clutch cmp comm csplit curl curl-config cut cycc cydown cynject db_archive db_checkpoint db_codegen db_deadlock db_dump db_hotbackup db_load db_printlog db_recover db_stat db_upgrade db_verify df diff diff3 dircolors dirname dpkg dpkg-deb dpkg-divert dpkg-maintscript-helper dpkg-query dpkg-split dpkg-statoverride dpkg-trigger dselect du env expand expr factor find fmt fold funzip gawk getconf getty gpg gpg-zip gpgsplit gpgv groups gssc head hostid hostinfo id igawk infocmp infotocap install iofbres iomfsetgamma join killall ldid ldrestart link locate login logname lzcat lzcmp lzdiff lzegrep lzfgrep lzgrep lzless lzma lzmadec lzmainfo lzmore md5sum mkfifo mktemp ncurses5-config ncursesw5-config nice nl nohup nproc nvnonce od openssl pagesize passwd paste pathchk pinky pr printenv printf ptx quota redeb renice reset rsync runcon sbdidlaunch sbreload scp script sdiff seq sftp sha1sum sha224sum sha256sum sha384sum sha512sum shred shuf slogin sort split ssh ssh-add ssh-agent ssh-keygen ssh-keyscan sshpass stat sudo sudoedit sum sw_vers tac tail tar tee test tic time timeout toe tput tr truncate tset tsort tty uicache uiduid uiopen unexpand uniq unlink unlzma unrar unzip unzipsfx update-alternatives updatedb uptime users wc which who whoami xargs yes zip zipcloak zipnote zipsplit
cd /mnt1/usr/lib && rm -rf SmartTapPs.dylib _ncurses apt coreutils cycript0.9 dpkg engines libapplist.dylib libapt-inst.dylib libapt-inst.dylib.1.1 libapt-inst.dylib.1.1.0 libapt-pkg.dylib libapt-pkg.dylib.4.6 libapt-pkg.dylib.4.6.0 libcrypto.0.9.8.dylib libcrypto.dylib libcurl.4.dylib libcurl.dylib libcurl.la libcurses.dylib libdb-4.6.dylib libdb-4.6.la libdb-4.dylib libdb.dylib libdpkg.a libdpkg.la libform.5.dylib libform.dylib libformw.5.dylib libformw.dylib libhistory.5.2.dylib libhistory.5.dylib libhistory.6.0.dylib libhistory.6.dylib libhistory.dylib liblzmadec.0.0.0.dylib liblzmadec.0.dylib liblzmadec.dylib liblzmadec.la libmenu.5.dylib libmenu.dylib libmenuw.5.dylib libmenuw.dylib libncurses.5.dylib libncurses.dylib libncursesw.5.dylib libncursesw.dylib libpam.1.0.dylib libpam.1.dylib libpam.dylib libpam_misc.1.dylib libpam_misc.dylib libpamc.1.dylib libpamc.dylib libpanel.5.dylib libpanel.dylib libpanelw.5.dylib libpanelw.dylib libpatcyh.dylib libprefs.dylib libreadline.5.2.dylib libreadline.5.dylib libreadline.6.0.dylib libreadline.6.dylib libreadline.dylib librocketbootstrap.dylib libssl.0.9.8.dylib libssl.dylib libst3.dylib libst3UI.dylib libsubstrate.0.dylib libsubstrate.dylib p7zip pam pkgconfig ssl terminfo xxxMobileGestalt.dylib xxxSystem.dylib
cd /mnt1/usr/libexec && rm -rf CrashHousekeeping MSUnrestrictProcess _rocketd_reenable afc2d awk bigram code cydia filza frcode gnupg loadruncmd rmt rocketd sftp-server ssh-keysign ssh-pkcs11-helper sshd-keygen-wrapper substrate sudo_noexec.dylib sudo_noexec.la vndevice && mv CrashHousekeeping_o CrashHousekeeping
cd /mnt1/usr/sbin && rm -rf ac accton chown chroot dev_mkdb edquota fdisk ioalloccount ioclasscount ioreg iostat mkfile pwd_mkdb quot quotaon repquota sshd startupfiletool sysctl update vifs vipw visudo vsdbutil zdump zic
cd /mnt1/usr/share && rm -rf awk bigboss dict dpkg gnupg tabset terminfo
cd /mnt1/bin && rm -rf bash bunzip2 bzcat bzip2 bzip2recover cat chgrp chmod chown cp date dd dir echo egrep false fgrep grep gunzip gzexe gzip kill ln ls mkdir mknod mktemp mv pwd readlink rm rmdir run-parts sed sh sleep stty su sync tar touch true uname uncompress vdir zcat zcmp zdiff zegrep zfgrep zforce zgrep zless zmore znew
rm "$(find /mnt1 -name 8.x_wtfis_ramdisk.sh)"